name: iot_air_monitor
description: IoT Air Quality Monitor - Firebase Version replacing Blynk

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_database: ^10.4.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4

  # UI dependencies
  cupertino_icons: ^1.0.2
  
  # Charts and visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.41
  
  # Network and HTTP
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  
  # Animations and UI enhancements
  lottie: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_staggered_animations: ^1.1.1
  
  # Icons and images
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # Custom fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700