// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // TODO: Get Web API key and App ID from Firebase Console
    apiKey: 'AIzaSyDL1iwM9wuJzg2fw2mP-aIM69Y16fU6Kdg',
    appId: '1:537162740770:web:cd386961de8dc193c3467b',
    messagingSenderId: '537162740770',
    projectId: 'iotsmart-7a145',
    authDomain: 'iotsmart-7a145.firebaseapp.com',
    databaseURL: 'https://iotsmart-7a145-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmart-7a145.firebasestorage.app',
    measurementId: 'G-8TCSRL582M', // Optional, from Google Analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDntHJ1ncMgoyVr39BrFA3T2xtrvz5ZD7g',
    appId: '1:537162740770:android:eeb1fb95ac25e897c3467b',
    messagingSenderId: '537162740770',
    projectId: 'iotsmart-7a145',
    authDomain: 'iotsmart-7a145.firebaseapp.com',
    databaseURL: 'https://iotsmart-7a145-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iotsmart-7a145.firebasestorage.app',
    androidClientId: 'WEB_CLIENT_ID_FROM_GOOGLE_AUTH.apps.googleusercontent.com', // TODO: Update with real client ID
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'demo-ios-api-key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'iot-air-quality-demo',
    databaseURL: 'https://iot-air-quality-demo-default-rtdb.firebaseio.com',
    storageBucket: 'iot-air-quality-demo.appspot.com',
    iosBundleId: 'com.example.iotAirQualityMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-macos-api-key',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'iot-air-quality-demo',
    databaseURL: 'https://iot-air-quality-demo-default-rtdb.firebaseio.com',
    storageBucket: 'iot-air-quality-demo.appspot.com',
    iosBundleId: 'com.example.iotAirQualityMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-windows-api-key',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'iot-air-quality-demo',
    databaseURL: 'https://iot-air-quality-demo-default-rtdb.firebaseio.com',
    storageBucket: 'iot-air-quality-demo.appspot.com',
  );
}
